imports:
    - cloudify.types

# The blueprint contains two nodes, a vm and a web server hosted in it.
blueprint:
    name: void_blueprint
    nodes:
    - name: node_1
      type: cloudify.types.web_server
      instances:
          deploy: 3
    - name: node_2
      type: cloudify.types.web_server
      relationships:
        - target: node_1
          type: cloudify.relationships.contained_in
    - name: node_3
      type: cloudify.types.app_server
      relationships:
        - target: node_1
          type: cloudify.relationships.contained_in
        - target: node_2
          type: cloudify.relationships.connected_to
    - name: node_4
      type: cloudify.types.app_server
      relationships:
        - target: node_3
          type: cloudify.relationships.contained_in
    - name: node_5
      type: cloudify.types.db_server
      relationships:
        - target: node_4
          type: cloudify.relationships.contained_in
    - name: node_6
      type: cloudify.types.db_server
      relationships:
        - target: node_5
          type: cloudify.relationships.contained_in
    - name: node_7
      type: cloudify.types.app_module
      relationships:
        - target: node_6
          type: cloudify.relationships.contained_in
        - target: node_5
          type: cloudify.relationships.connected_to