#######
# Cloudify Blueprint which describes a virtual machine with a simple Python
# HTTP server running on it.
# 

# The following import contains nodes implementation details
imports:
    - helloNeutron.yaml

# The blueprint contains two nodes, a vm and a web server hosted in it.
blueprint:
    name: hello_neutron
    nodes:
        -   name: app_network
            type: cloudify.types.network

        -   name: app_subnet
            type: cloudify.types.subnet
            relationships:
                - type: cloudify.relationships.contained_in
                  target: app_network
                  

        -   name: front_host
            type: cloudify.types.host
            relationships:
                - type: cloudify.relationships.connected_to
                  target: app_network

        -   name: http_web_server
            type: cloudify.types.web_server
            properties:
                port: 8080
            relationships:
                -   type: cloudify.relationships.contained_in
                    target: front_host
