'use strict';

/**
 * @ngdoc service
 * @name cosmoUiAppApp.cloudifyLoginInterceptor
 * @description
 * # cloudifyLoginInterceptor
 * Factory in the cosmoUiAppApp.
 */
angular.module('cosmoUiApp')
    .factory('cloudifyLoginInterceptor', function ( $log , $q, user ) {
        return {
            'responseError': function (rejection) {

                $log.info('got bad response', rejection);

                var errorCode = null;
                try{
                    var responseBody = rejection.data;
                    if ( typeof(responseBody) === 'string' ) {
                        responseBody = JSON.parse(responseBody);
                    }
                    errorCode = responseBody.error_code;
                }catch(e){
                    // this is a valid situation no need to print anything
                }

                // unauthenticated_error - is an error code generated by the ui
                // the rest service returns unauthorized even if user is unauthenticated. ui needs to differentiate between the two.
                if (rejection.status === 401 && errorCode === 'unauthenticated_error') { // this is a cloudify standard response for authentication.lets redirect to login
                    $log.info('redirecting to login page');
                    // we cannot use $http or anything here.
                    window.location.hash = '#/login';
                    return;
                }

                return $q.reject(rejection);
            }
        };
    });
